@baseURL = "http://localhost:3000/"

//Login
// headers: Content-Type
POST {{baseURL}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "admin123"
}

###

//Google Sign In
POST {{baseURL}}/api/auth/google HTTP/1.1