// get categories
GET {{baseURL}}/api/categories HTTP/1.1

###
// get a category by id
// params: id
GET {{baseURL}}/api/categories/6234914debfdc31dc19e25b3 HTTP/1.1

###

// create a new category
// headers: x-token, Content-Type
// body: {name: String}
POST {{baseURL}}/api/categories HTTP/1.1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjI3ZjE5NDQxYWJjNDQwYzYzOTMwZmYiLCJpYXQiOjE2NDc2MTA3MTAsImV4cCI6MTY0NzYyNTExMH0.wQmIkw8Ap2boXAu6DJ8SvAEyvdVI1PyRkP74pJqWhdw

{
    "name": "embutidos"
}

###

// Update a category
// params: id
// headers: x-token, Content-Type
// body: {name: String, user: mongoId}
PUT {{baseURL}}/api/categories/6234914debfdc31dc19e25b3 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjI3ZjE5NDQxYWJjNDQwYzYzOTMwZmYiLCJpYXQiOjE2NDc2MTc1OTIsImV4cCI6MTY0NzYzMTk5Mn0.gb0w_LIrhTdkDuZwIcK_4ILNA6ThVIvy7bZHAIsAmXA
Content-Type: application/json

{
    "name": "lácteos",
    "user": "62251454456dafc61ec8c43d"
}

###

// Delete a category
// params: id
// headers: x-token
DELETE {{baseURL}}/api/categories/6234a5fd1a76e3e5a5b0b7e0 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjI3ZjE5NDQxYWJjNDQwYzYzOTMwZmYiLCJpYXQiOjE2NDc2MTc1OTIsImV4cCI6MTY0NzYzMTk5Mn0.gb0w_LIrhTdkDuZwIcK_4ILNA6ThVIvy7bZHAIsAmXA