@baseURL = http://localhost:3000

// Get users - paginate
// querys: limit=5, skip=0
GET {{baseURL}}/api/users?limit=10&skip=1 HTTP/1.1

###
// Get user by id
// params: id
GET {{baseURL}}/api/users/62251454456dafc61ec8c43d HTTP/1.1

###

//Create users
// headers: Content-Type
// body: {name: String, email: String, password: String, role: enum}
POST {{baseURL}}/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "joedoe",
  "email": "doe@test.com",
  "password": "joedoe.123",
  "role": "USER_ROLE" //this property can be changed to USER_ROLE, ADMIN_ROLE or SALES_ROLE
}

###

// Update one user
// params: id
// headers: Content-Type
// body: {name: String, email: String, password: String, role: enum, google_auth: Boolean}
PUT {{baseURL}}/api/users/62238d10ce4f8720d9ddb5c1 HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "test12345",
    "role": "USER_ROLE",
    "google_auth": true
}

###

// Delete one user
// params: id
// headers : x-token
DELETE {{baseURL}}/api/users/622fc5ab4fe7c37d13513072 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjI3ZjE5NDQxYWJjNDQwYzYzOTMwZmYiLCJpYXQiOjE2NDcyOTg3MjksImV4cCI6MTY0NzMxMzEyOX0.ZeDhdZLUsDUiMV2SxR33_SKVhAsq-p8l6CVvoJEB0pE
